stages:
  - check
  - test

check-code:
  stage: check
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/check_java.sh\""
  artifacts:
    when: always
    paths:
      - "core/build/reports"
      - "prov/build/reports"
      - "pg/build/reports"
      - "pkix/build/reports"
      - "mail/build/reports"
      - "util/build/reports"
      - "tls/build/reports"  
  
test-code-8:
  stage: test
  needs: []
  script:
   - "ecr_login"
   - "ecr_pull vm_base_intel latest"
   - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/test_8.sh\""
  artifacts:
    when: always
    paths:
      - "core/build/reports"
      - "prov/build/reports"
      - "pg/build/reports"
      - "pkix/build/reports"
      - "mail/build/reports"
      - "util/build/reports"
      - "tls/build/reports"  
  
test-code-11:
  stage: test
  needs: []
  script:
   - "ecr_login"
   - "ecr_pull vm_base_intel latest"
   - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/test_11.sh\""
  artifacts:
    when: always
    paths:
      - "core/build/reports"
      - "prov/build/reports"
      - "pg/build/reports"
      - "pkix/build/reports"
      - "mail/build/reports"
      - "util/build/reports"
      - "tls/build/reports"  
  
test-code-17:
  stage: test
  script:
   - "ecr_login"
   - "ecr_pull vm_base_intel latest"
   - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/test_17.sh\""
  artifacts:
    when: always
    paths:
      - "core/build/reports"
      - "prov/build/reports"
      - "pg/build/reports"
      - "pkix/build/reports"
      - "mail/build/reports"
      - "util/build/reports"
      - "tls/build/reports"  
test-code-21:
  stage: test
  needs: []
  script:
    - "ecr_login"
    - "ecr_pull vm_base_intel latest"
    - "ci_docker_run \"vm_base_intel:latest\" \"bc-java\" \"/workspace/bc-java/ci/test_21.sh\""
  artifacts:
    when: always
    paths:
      - "core/build/reports"
      - "prov/build/reports"
      - "pg/build/reports"
      - "pkix/build/reports"
      - "mail/build/reports"
      - "util/build/reports"
      - "tls/build/reports"